// <auto-generated />
using DomainModel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DomainModel.Migrations
{
    [DbContext(typeof(SystemContext))]
    partial class SystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DomainModel.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Cairo, Nasr City",
                            CustomerName = "Customer1"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Cairo, Maadi",
                            CustomerName = "Customer2"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Cairo, 5th Settlement",
                            CustomerName = "Customer3"
                        });
                });

            modelBuilder.Entity("DomainModel.Models.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("RegisterNumber")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("ShowStatus")
                        .HasColumnType("bit");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = "YS2R4X20005399401",
                            CustomerId = 1,
                            RegisterNumber = "ABC123",
                            ShowStatus = false
                        },
                        new
                        {
                            VehicleId = "VLUR4X20009093588",
                            CustomerId = 1,
                            RegisterNumber = "DEF456",
                            ShowStatus = false
                        },
                        new
                        {
                            VehicleId = "VLUR4X20009048066",
                            CustomerId = 1,
                            RegisterNumber = "GHI789",
                            ShowStatus = false
                        },
                        new
                        {
                            VehicleId = "YS2R4X20005388011",
                            CustomerId = 2,
                            RegisterNumber = "JKL012",
                            ShowStatus = false
                        },
                        new
                        {
                            VehicleId = "YS2R4X20005387949",
                            CustomerId = 2,
                            RegisterNumber = "MNO345",
                            ShowStatus = false
                        },
                        new
                        {
                            VehicleId = "YS2R4X20005387765",
                            CustomerId = 3,
                            RegisterNumber = "PQR678",
                            ShowStatus = false
                        },
                        new
                        {
                            VehicleId = "YS2R4X20005387055",
                            CustomerId = 3,
                            RegisterNumber = "STU901",
                            ShowStatus = false
                        });
                });

            modelBuilder.Entity("DomainModel.Models.Vehicle", b =>
                {
                    b.HasOne("DomainModel.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("PK_Vehicle_Customer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DomainModel.Models.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
